"""add whatsapp models

Revision ID: 0eda7a39bd4d
Revises: cb185428b977
Create Date: 2026-03-13 16:05:38.424743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eda7a39bd4d'
down_revision = 'cb185428b977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('opt_in_status', sa.Boolean(), nullable=False),
    sa.Column('opt_in_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_phone_number'), ['phone_number'], unique=True)

    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waba_id', sa.String(length=128), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('header_type', sa.String(length=32), nullable=True),
    sa.Column('header_content', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('footer_text', sa.Text(), nullable=True),
    sa.Column('buttons', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_template_name'), ['template_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_templates_waba_id'), ['waba_id'], unique=False)

    op.create_table('waba_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('phone_number_id', sa.String(length=128), nullable=False),
    sa.Column('waba_id', sa.String(length=128), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('webhook_verify_token', sa.String(length=255), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('waba_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waba_accounts_phone_number_id'), ['phone_number_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_waba_accounts_waba_id'), ['waba_id'], unique=False)

    op.create_table('webhooks_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhooks_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhooks_log_processed'), ['processed'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('session_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_status'), ['status'], unique=False)

    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_groups_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_groups_name'), ['name'], unique=False)

    op.create_table('group_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'contact_id', name='uq_group_contacts_group_contact')
    )
    with op.batch_alter_table('group_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_contacts_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_contacts_group_id'), ['group_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('wamid', sa.String(length=191), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_wamid'), ['wamid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_wamid'))
        batch_op.drop_index(batch_op.f('ix_messages_type'))
        batch_op.drop_index(batch_op.f('ix_messages_template_id'))
        batch_op.drop_index(batch_op.f('ix_messages_status'))
        batch_op.drop_index(batch_op.f('ix_messages_direction'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_messages_contact_id'))

    op.drop_table('messages')
    with op.batch_alter_table('group_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_contacts_group_id'))
        batch_op.drop_index(batch_op.f('ix_group_contacts_contact_id'))

    op.drop_table('group_contacts')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_groups_name'))
        batch_op.drop_index(batch_op.f('ix_groups_created_by'))

    op.drop_table('groups')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_status'))
        batch_op.drop_index(batch_op.f('ix_conversations_contact_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('webhooks_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhooks_log_processed'))

    op.drop_table('webhooks_log')
    with op.batch_alter_table('waba_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waba_accounts_waba_id'))
        batch_op.drop_index(batch_op.f('ix_waba_accounts_phone_number_id'))

    op.drop_table('waba_accounts')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_waba_id'))
        batch_op.drop_index(batch_op.f('ix_templates_template_name'))

    op.drop_table('templates')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_phone_number'))

    op.drop_table('contacts')
    # ### end Alembic commands ###
