"""add grp msg

Revision ID: 2c30e4a61ed5
Revises: cd2a125b34a6
Create Date: 2026-03-17 18:17:45.863788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c30e4a61ed5'
down_revision = 'cd2a125b34a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waba_account_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('template_payload', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['waba_account_id'], ['waba_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_messages_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_messages_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_messages_message_type'), ['message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_messages_waba_account_id'), ['waba_account_id'], unique=False)

    op.create_table('group_message_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waba_account_id', sa.Integer(), nullable=True),
    sa.Column('group_message_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=191), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['group_message_id'], ['group_messages.id'], ),
    sa.ForeignKeyConstraint(['waba_account_id'], ['waba_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_message_recipients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_message_recipients_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_message_recipients_group_message_id'), ['group_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_message_recipients_provider_message_id'), ['provider_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_message_recipients_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_message_recipients_waba_account_id'), ['waba_account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_message_recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_message_recipients_waba_account_id'))
        batch_op.drop_index(batch_op.f('ix_group_message_recipients_status'))
        batch_op.drop_index(batch_op.f('ix_group_message_recipients_provider_message_id'))
        batch_op.drop_index(batch_op.f('ix_group_message_recipients_group_message_id'))
        batch_op.drop_index(batch_op.f('ix_group_message_recipients_contact_id'))

    op.drop_table('group_message_recipients')
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_messages_waba_account_id'))
        batch_op.drop_index(batch_op.f('ix_group_messages_message_type'))
        batch_op.drop_index(batch_op.f('ix_group_messages_group_id'))
        batch_op.drop_index(batch_op.f('ix_group_messages_created_by'))
        batch_op.drop_index(batch_op.f('ix_group_messages_created_at'))

    op.drop_table('group_messages')
    # ### end Alembic commands ###
