"""add waba link

Revision ID: 7adfdbf6a344
Revises: 0eda7a39bd4d
Create Date: 2026-03-13 16:10:25.085453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7adfdbf6a344'
down_revision = '0eda7a39bd4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waba_account_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_contacts_waba_account_id'), ['waba_account_id'], unique=False)
        batch_op.create_foreign_key(None, 'waba_accounts', ['waba_account_id'], ['id'])

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waba_account_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_conversations_waba_account_id'), ['waba_account_id'], unique=False)
        batch_op.create_foreign_key(None, 'waba_accounts', ['waba_account_id'], ['id'])

    with op.batch_alter_table('group_contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waba_account_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_group_contacts_waba_account_id'), ['waba_account_id'], unique=False)
        batch_op.create_foreign_key(None, 'waba_accounts', ['waba_account_id'], ['id'])

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waba_account_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_groups_waba_account_id'), ['waba_account_id'], unique=False)
        batch_op.create_foreign_key(None, 'waba_accounts', ['waba_account_id'], ['id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waba_account_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_messages_waba_account_id'), ['waba_account_id'], unique=False)
        batch_op.create_foreign_key(None, 'waba_accounts', ['waba_account_id'], ['id'])

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waba_account_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_templates_waba_account_id'), ['waba_account_id'], unique=False)
        batch_op.create_foreign_key(None, 'waba_accounts', ['waba_account_id'], ['id'])

    with op.batch_alter_table('waba_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_waba_accounts_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('webhooks_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waba_account_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_webhooks_log_waba_account_id'), ['waba_account_id'], unique=False)
        batch_op.create_foreign_key(None, 'waba_accounts', ['waba_account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhooks_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_webhooks_log_waba_account_id'))
        batch_op.drop_column('waba_account_id')

    with op.batch_alter_table('waba_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_waba_accounts_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_templates_waba_account_id'))
        batch_op.drop_column('waba_account_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_messages_waba_account_id'))
        batch_op.drop_column('waba_account_id')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_groups_waba_account_id'))
        batch_op.drop_column('waba_account_id')

    with op.batch_alter_table('group_contacts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_group_contacts_waba_account_id'))
        batch_op.drop_column('waba_account_id')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_conversations_waba_account_id'))
        batch_op.drop_column('waba_account_id')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_contacts_waba_account_id'))
        batch_op.drop_column('waba_account_id')

    # ### end Alembic commands ###
